analyzer:
  errors:
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  
  # `// ignore: name_of_lint`
  # `// ignore_for_file: name_of_lint`
  rules:
    # avoid_print: false 
    # prefer_single_quotes: true
