name: taralibrary
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  flutter_carousel_widget: ^3.0.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/air-freshener.svg
    - assets/icons/angle-small-left.svg
    - assets/icons/books.svg
    - assets/icons/chart-histogram.svg
    - assets/icons/chart-histogram-solid.svg
    - assets/icons/computer-classic.svg
    - assets/icons/desk.svg
    - assets/icons/heart.svg
    - assets/icons/home-solid.svg
    - assets/icons/home.svg
    - assets/icons/map-marker.svg
    - assets/icons/map-marker-solid.svg
    - assets/icons/router-wifi.svg
    - assets/icons/star.svg
    - assets/icons/user-solid.svg
    - assets/icons/user.svg
    - assets/icons/search.svg
    - assets/icons/arrow-trend-up.svg
    - assets/icons/ellipse.png
    - assets/icons/small-ellipse.png

    - assets/icons/sign-out-alt-outline.svg
    - assets/icons/sign-out-alt-solid.svg
    - assets/icons/lock.svg


    - assets/images/avatar-1.jpg
    - assets/images/avatar-2.jpg
    - assets/images/avatar-3.jpg
    - assets/images/1.jfif
    - assets/images/2.jfif
    - assets/images/3.jfif
    - assets/images/4.jfif
    - assets/images/5.jfif
    - assets/images/6.jfif
    - assets/images/7.jfif